print('trial3: Information after trial')
print('trial3: Information here')
print('trial3: Information again')
print('trial3: Information again')
print('trial3: Information again')
print('trial3: Information again')
print('trial3: Information again')
print('trial3: Information again')